import { Movie } from "../models/movie.model";

export const MockMovies: Partial<Movie>[] = [
  {
    title: 'Always Be My Maybe',
    release_year: 2019,
    location: '717 Grant Ave',
    fun_facts: '',
    production_company: 'Isla Productions, LLC',
    distributor: 'Netflix',
    director: 'Nahnatchka Khan',
    writer: 'Michael Golamco, Randall Park, Ali Wong',
    actor_1: ['Ali Wong', 'Randall Park', 'Keanu Reeves'],
    lat: 37.7936544,
    lng: -122.4063975,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'DEVS',
    release_year: 2020,
    location: 'Filbert btwn Powell and Stockton',
    fun_facts: '',
    production_company: 'Minim Productions',
    distributor: 'FX Network',
    director: 'Alex Garland',
    writer: 'Alex Garland',
    actor_1: 'Sonoya Mizuno',
    lat: 37.801299,
    lng: -122.4111093,
    analysis_neighborhood: 'North Beach',
  },
  {
    title: 'Romeo Must Die',
    release_year: 2000,
    location: 'Embarcadero Street',
    fun_facts: '',
    production_company: 'Silver Pictures',
    distributor: 'Warner Bros. Pictures',
    director: 'Andrzej Bartkowiak',
    writer: 'Mitchell Kapner',
    actor_1: ['Jet Li', 'Aaliyah'],
    lat: 37.8009724,
    lng: -122.3990319,
    analysis_neighborhood: 'Financial District/South Beach',
  },
  {
    title: 'San Andreas',
    release_year: 2015,
    location: 'Fort Baker',
    fun_facts: '',
    production_company: 'Upside Down Productions, Inc.',
    distributor: 'Warner Bros.',
    director: 'Brad Peyton',
    writer: 'Allan Loeb',
    actor_1: ['Dwayne Johnson'],
    lat: 37.8360614,
    lng: -122.4788979,
    analysis_neighborhood: '',
  },
  {
    title: 'Chance- Season 1 ep103',
    release_year: 2016,
    location: '17th and Arkansas',
    fun_facts: '',
    production_company: 'TVM Productions',
    distributor: 'HULU',
    director: 'Michael Lehmann',
    writer: 'Kem Nunn',
    actor_1: ['Hugh Laurie', 'Gretchen Mol', 'Ethan Suplee'],
    lat: 37.765027,
    lng: -122.3987241,
    analysis_neighborhood: 'Mission Bay',
  },
  {
    title: 'Getting Even with Dad',
    release_year: 1994,
    location: 'California & Grant Streets',
    fun_facts: '',
    production_company: 'Metro-Goldwyn-Mayer (MGM)',
    distributor: 'Metro-Goldwyn-Mayer (MGM)',
    director: 'Howard Dutch',
    writer: 'Tom S. Parker',
    actor_1: ['Macaulay Culkin', 'Ted Danson'],
    lat: 37.7924672,
    lng: -122.4059509,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'The Matrix Resurrections',
    release_year: 2021,
    location: 'California at Grant Ave',
    fun_facts: '',
    production_company: 'Adobe Pictures, Inc.',
    distributor: 'Warner Brothers',
    director: 'Lana Wachowski',
    writer: 'Lana Wachowski, David Mitchell, Aleksander Hemon',
    actor_1: ['Keanu Reeves', 'Neil Patrick Harris'],
    lat: 37.7924672,
    lng: -122.4059509,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'DEVS',
    release_year: 2020,
    location: 'Brannan btwn 3rd and 6th St',
    fun_facts: '',
    production_company: 'Minim Productions',
    distributor: 'FX Network',
    director: 'Alex Garland',
    writer: 'Alex Garland',
    actor_1: ['Sonoya Mizuno', 'Nick Offerman', 'Jin Ha'],
    lat: 37.7789746,
    lng: -122.3962823,
    analysis_neighborhood: 'South of Market',
  },
  {
    title: 'The Towering Inferno',
    release_year: 1974,
    location: 'Fairmont Hotel (950 Mason Street, Nob Hill)',
    fun_facts: 'In 1945 the Fairmont hosted the United Nations Conference on International Organization.',
    production_company: 'Irwin Allen Productions',
    distributor: 'Twentieth Century - Fox',
    director: 'John Guillermin',
    writer: 'Stirling Silliphant',
    actor_1: ['Steve McQueen', 'Paul Newman', 'William Holden'],
    lat: 37.7923883,
    lng: -122.4100923,
    analysis_neighborhood: 'Nob Hill',
  },
  {
    title: 'Fearless',
    release_year: 1993,
    location: '400 Montgomery Street',
    fun_facts: '',
    production_company: 'Spring Creek Productions',
    distributor: 'Warner Bros. Pictures',
    director: 'Peter Weir',
    writer: 'Rafael Yglesias',
    actor_1: ['Jeff Bridges', 'Isabella Rosellini', 'Rosie Perez'],
    lat: 37.7931137,
    lng: -122.402597,
    analysis_neighborhood: 'Financial District/South Beach',
  }, {
    title: 'Always Be My Maybe',
    release_year: 2019,
    location: '717 Grant Ave',
    fun_facts: '',
    production_company: 'Isla Productions, LLC',
    distributor: 'Netflix',
    director: 'Nahnatchka Khan',
    writer: 'Michael Golamco, Randall Park, Ali Wong',
    actor_1: ['Ali Wong', 'Randall Park', 'Keanu Reeves'],
    lat: 37.7936544,
    lng: -122.4063975,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'DEVS',
    release_year: 2020,
    location: 'Filbert btwn Powell and Stockton',
    fun_facts: '',
    production_company: 'Minim Productions',
    distributor: 'FX Network',
    director: 'Alex Garland',
    writer: 'Alex Garland',
    actor_1: 'Sonoya Mizuno',
    lat: 37.801299,
    lng: -122.4111093,
    analysis_neighborhood: 'North Beach',
  },
  {
    title: 'Romeo Must Die',
    release_year: 2000,
    location: 'Embarcadero Street',
    fun_facts: '',
    production_company: 'Silver Pictures',
    distributor: 'Warner Bros. Pictures',
    director: 'Andrzej Bartkowiak',
    writer: 'Mitchell Kapner',
    actor_1: ['Jet Li', 'Aaliyah'],
    lat: 37.8009724,
    lng: -122.3990319,
    analysis_neighborhood: 'Financial District/South Beach',
  },
  {
    title: 'San Andreas',
    release_year: 2015,
    location: 'Fort Baker',
    fun_facts: '',
    production_company: 'Upside Down Productions, Inc.',
    distributor: 'Warner Bros.',
    director: 'Brad Peyton',
    writer: 'Allan Loeb',
    actor_1: ['Dwayne Johnson'],
    lat: 37.8360614,
    lng: -122.4788979,
    analysis_neighborhood: '',
  },
  {
    title: 'Chance- Season 1 ep103',
    release_year: 2016,
    location: '17th and Arkansas',
    fun_facts: '',
    production_company: 'TVM Productions',
    distributor: 'HULU',
    director: 'Michael Lehmann',
    writer: 'Kem Nunn',
    actor_1: ['Hugh Laurie', 'Gretchen Mol', 'Ethan Suplee'],
    lat: 37.765027,
    lng: -122.3987241,
    analysis_neighborhood: 'Mission Bay',
  },
  {
    title: 'Getting Even with Dad',
    release_year: 1994,
    location: 'California & Grant Streets',
    fun_facts: '',
    production_company: 'Metro-Goldwyn-Mayer (MGM)',
    distributor: 'Metro-Goldwyn-Mayer (MGM)',
    director: 'Howard Dutch',
    writer: 'Tom S. Parker',
    actor_1: ['Macaulay Culkin', 'Ted Danson'],
    lat: 37.7924672,
    lng: -122.4059509,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'The Matrix Resurrections',
    release_year: 2021,
    location: 'California at Grant Ave',
    fun_facts: '',
    production_company: 'Adobe Pictures, Inc.',
    distributor: 'Warner Brothers',
    director: 'Lana Wachowski',
    writer: 'Lana Wachowski, David Mitchell, Aleksander Hemon',
    actor_1: ['Keanu Reeves', 'Neil Patrick Harris'],
    lat: 37.7924672,
    lng: -122.4059509,
    analysis_neighborhood: 'Chinatown',
  },
  {
    title: 'DEVS',
    release_year: 2020,
    location: 'Brannan btwn 3rd and 6th St',
    fun_facts: '',
    production_company: 'Minim Productions',
    distributor: 'FX Network',
    director: 'Alex Garland',
    writer: 'Alex Garland',
    actor_1: ['Sonoya Mizuno', 'Nick Offerman', 'Jin Ha'],
    lat: 37.7789746,
    lng: -122.3962823,
    analysis_neighborhood: 'South of Market',
  },
  {
    title: 'The Towering Inferno',
    release_year: 1974,
    location: 'Fairmont Hotel (950 Mason Street, Nob Hill)',
    fun_facts: 'In 1945 the Fairmont hosted the United Nations Conference on International Organization.',
    production_company: 'Irwin Allen Productions',
    distributor: 'Twentieth Century - Fox',
    director: 'John Guillermin',
    writer: 'Stirling Silliphant',
    actor_1: ['Steve McQueen', 'Paul Newman', 'William Holden'],
    lat: 37.7923883,
    lng: -122.4100923,
    analysis_neighborhood: 'Nob Hill',
  },
  {
    title: 'Fearless',
    release_year: 1993,
    location: '400 Montgomery Street',
    fun_facts: '',
    production_company: 'Spring Creek Productions',
    distributor: 'Warner Bros. Pictures',
    director: 'Peter Weir',
    writer: 'Rafael Yglesias',
    actor_1: ['Jeff Bridges', 'Isabella Rosellini', 'Rosie Perez'],
    lat: 37.7931137,
    lng: -122.402597,
    analysis_neighborhood: 'Financial District/South Beach',
  },
    {
    title: 'Fearless',
    release_year: 1993,
    location: '400 Montgomery Street',
    fun_facts: '',
    production_company: 'Spring Creek Productions',
    distributor: 'Warner Bros. Pictures',
    director: 'Peter Weir',
    writer: 'Rafael Yglesias',
    actor_1: ['Jeff Bridges', 'Isabella Rosellini', 'Rosie Perez'],
    lat: 37.7931137,
    lng: -122.402597,
    analysis_neighborhood: 'Financial District/South Beach',
  }
];